# Generated by Django 5.0.1 on 2024-01-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=255, verbose_name='Должность')),
                ('content', models.TextField(blank=True, verbose_name='Достижения')),
                ('task', models.TextField(blank=True, verbose_name='Обязанности')),
                ('place', models.TextField(blank=True, verbose_name='Место работы')),
                ('begin', models.DateField(blank=True, verbose_name='Начало работы')),
                ('finish', models.DateField(blank=True, verbose_name='Конец работы')),
                ('doc', models.FileField(upload_to='file/%Y/%m/%d/', verbose_name='Файлы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='progress.category', verbose_name='Категории')),
            ],
        ),
    ]
